from fractions import fraction

a = fraction(3, -4)
b = fraction(4, 3)
c = fraction(1, 2)
d = fraction(-2, 5)
e = fraction(6, 2)
f = fraction(1)
g = fraction(0)
h = fraction(3)
i = fraction(-2, 3)
j = fraction(-1, 3)
k = fraction(-1)
l = fraction(7, 12)
m = fraction(14, 15)
n = fraction(7, 2)
o = fraction(-23, 20)
p = fraction(4)
q = fraction(-3, 8)
r = fraction(-8, 15)
s = fraction(9)
t = fraction(1, 1, 3)

def SumTestCases():    
    yield (i, j, k)
    yield (a, b, l)
    yield (b, d, m)
    yield (c, e, n)
    yield (a, d, o)
    yield (f, g, f)
    yield (g, g, g)
    yield (h, f, p)
    yield (b, g, t)

def ProductTestCases():
    yield (a, b, k)
    yield (a, c, q)
    yield (b, d, r)
    yield (b, g, g)
    yield (e, e, s)